/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/cities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List enabled cities */
    get: operations['listCities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List current event occurrences for one city and named time window
     * @description Omitting window selects upcoming. Upcoming is bounded to the next 90 local calendar days. All windows exclude occurrences that ended at or before the first page's as_of anchor; ongoing timed and current all-day occurrences remain. Pages are ordered by effective start and occurrence ID. A signed cursor preserves the first-page anchor and active filters.
     */
    get: operations['listEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/events/{occurrence_id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        occurrence_id: components['parameters']['OccurrenceID'];
      };
      cookie?: never;
    };
    /** Get the current verified version of an event occurrence */
    get: operations['getEvent'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/events/{occurrence_id}/changes': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        occurrence_id: components['parameters']['OccurrenceID'];
      };
      cookie?: never;
    };
    /** List material public changes for an occurrence */
    get: operations['listEventChanges'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/events/{occurrence_id}.ics': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        occurrence_id: components['parameters']['OccurrenceID'];
      };
      cookie?: never;
    };
    /** Download the current occurrence as an iCalendar event */
    get: operations['downloadEventCalendar'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/sources/{source_slug}/summary': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_slug: string;
      };
      cookie?: never;
    };
    /** Get public freshness and authority information for a source */
    get: operations['getSourceSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/operator/sources': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List source health for operators */
    get: operations['listOperatorSources'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/operator/sources/{source_id}/runs': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: components['parameters']['SourceID'];
      };
      cookie?: never;
    };
    /** List recent collection runs for a source */
    get: operations['listCollectionRuns'];
    put?: never;
    /** Enqueue one manual source collection */
    post: operations['triggerCollectionRun'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/operator/runs/{run_id}/replay': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: components['parameters']['RunID'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Enqueue ingestion replay from an immutable stored artifact */
    post: operations['replayCollectionRun'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/operator/incidents/{incident_id}/acknowledge': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        incident_id: components['parameters']['IncidentID'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Acknowledge a source-health incident */
    post: operations['acknowledgeIncident'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CitySlug: string;
    /** @enum {unknown} */
    TimeWindow: 'upcoming' | 'today' | 'tomorrow' | 'weekend';
    /** @enum {unknown} */
    Category: 'arts' | 'talks' | 'theatre' | 'music' | 'books' | 'community' | 'other';
    /** @enum {unknown} */
    EventStatus: 'scheduled' | 'cancelled' | 'postponed';
    /** @enum {string|null} */
    RegistrationState: 'open' | 'sold_out' | 'closed' | 'not_required' | null;
    /** @enum {unknown} */
    Freshness: 'fresh' | 'stale';
    City: {
      slug: components['schemas']['CitySlug'];
      name: string;
      timezone: string;
      accent: string;
    };
    Timing: {
      /** Format: date */
      start_date: string;
      /** Format: date-time */
      starts_at: string | null;
      /** Format: date */
      end_date: string | null;
      /** Format: date-time */
      ends_at: string | null;
      /** @enum {unknown} */
      precision: 'timed' | 'date';
      /** @constant */
      timezone: 'Asia/Kolkata';
    } & unknown;
    Venue: {
      name: string;
      address: string | null;
    } | null;
    Pricing: {
      is_free: boolean | null;
      minimum_minor: number | null;
      maximum_minor: number | null;
      /** @enum {string|null} */
      currency: 'INR' | null;
    } & (unknown & unknown & unknown & unknown);
    Registration: {
      /** Format: uri */
      url: string | null;
      state: components['schemas']['RegistrationState'];
    };
    SourceReference: {
      slug: string;
      name: string;
      /** Format: uri */
      url: string;
      /** Format: hostname */
      host: string;
      freshness: components['schemas']['Freshness'];
    };
    EventSummary: {
      /** Format: uuid */
      id: string;
      slug: string;
      city: components['schemas']['City'];
      title: string;
      category: components['schemas']['Category'];
      timing: components['schemas']['Timing'];
      venue: components['schemas']['Venue'];
      pricing: components['schemas']['Pricing'];
      registration: components['schemas']['Registration'];
      status: components['schemas']['EventStatus'];
      /** Format: uri */
      image_url: string | null;
      source: components['schemas']['SourceReference'];
      /** Format: date-time */
      last_checked_at: string;
      /** @enum {string|null} */
      change_kind: 'new' | 'updated' | null;
      language: string[];
      age_note: string | null;
      accessibility_note: string | null;
    };
    EventDetail: components['schemas']['EventSummary'];
    EventPage: {
      items: components['schemas']['EventSummary'][];
      /** @description Signed continuation cursor; non-null exactly when meta.has_more is true. */
      next_cursor: string | null;
      meta: {
        city: components['schemas']['City'];
        window: components['schemas']['TimeWindow'];
        /** @description Total occurrences matching the anchored filters, not only this page. */
        result_count: number;
        source_count: number;
        /** Format: date-time */
        last_checked_at: string | null;
        /** @description Number of items returned in this page. */
        page_size: number;
        /** @description Whether a continuation page is available through next_cursor. */
        has_more: boolean;
        /**
         * Format: date-time
         * @description Stable request-time anchor carried by every cursor in this result set.
         */
        as_of: string;
      };
    };
    EventChange: {
      /** Format: uuid */
      id: string;
      /** @enum {unknown} */
      kind: 'updated' | 'cancelled' | 'postponed';
      changed_fields: ('timing' | 'venue' | 'pricing' | 'registration' | 'status')[];
      /** Format: date-time */
      changed_at: string;
    };
    SourceSummary: {
      slug: string;
      name: string;
      /** Format: uri */
      official_url: string;
      city: components['schemas']['City'];
      freshness: components['schemas']['Freshness'];
      /** Format: date-time */
      last_healthy_at: string | null;
    };
    OperatorSource: {
      /** Format: uuid */
      id: string;
      slug: string;
      name: string;
      /** Format: uri */
      official_url: string;
      city: components['schemas']['City'];
      freshness: components['schemas']['Freshness'];
      /** Format: date-time */
      last_healthy_at: string | null;
      collector_id: string;
      schema_version: string;
      /** @enum {unknown} */
      publication_state: 'active' | 'frozen' | 'disabled';
      /** Format: date-time */
      next_due_at: string | null;
      latest_run: components['schemas']['CollectionRun'] | null;
      active_incident: components['schemas']['Incident'] | null;
    };
    CollectionRun: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      source_id: string;
      external_collection_id: string | null;
      /** @enum {unknown} */
      status: 'queued' | 'collecting' | 'validating' | 'published' | 'rejected' | 'failed';
      /** Format: date-time */
      triggered_at: string;
      /** Format: date-time */
      completed_at: string | null;
      accepted_count: number;
      quarantined_count: number;
      health_code: string | null;
    };
    Incident: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      source_id: string;
      /** Format: uuid */
      run_id: string | null;
      code: string;
      /** @enum {unknown} */
      state: 'open' | 'acknowledged' | 'resolved';
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      acknowledged_at: string | null;
    };
    Problem: {
      /** Format: uri */
      type: string;
      title: string;
      status: number;
      detail?: string;
      /** Format: uri-reference */
      instance?: string;
      code: string;
    } & {
      [key: string]: unknown;
    };
  };
  responses: {
    /** @description RFC 9457 problem details */
    Problem: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
  };
  parameters: {
    CitySlug: components['schemas']['CitySlug'];
    OccurrenceID: string;
    SourceID: string;
    RunID: string;
    IncidentID: string;
    IdempotencyKey: string;
  };
  requestBodies: never;
  headers: {
    /** @description Entity tag for conditional requests */
    ETag: string;
  };
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listCities: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Enabled city choices */
      200: {
        headers: {
          ETag: components['headers']['ETag'];
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: components['schemas']['City'][];
          };
        };
      };
      default: components['responses']['Problem'];
    };
  };
  listEvents: {
    parameters: {
      query: {
        city: components['parameters']['CitySlug'];
        window?: components['schemas']['TimeWindow'];
        category?: components['schemas']['Category'][];
        /** @description When true, include only events explicitly marked free. */
        free?: boolean;
        cursor?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A stable, cursor-paginated event page */
      200: {
        headers: {
          ETag: components['headers']['ETag'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EventPage'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  getEvent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        occurrence_id: components['parameters']['OccurrenceID'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current occurrence */
      200: {
        headers: {
          ETag: components['headers']['ETag'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EventDetail'];
        };
      };
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  listEventChanges: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        occurrence_id: components['parameters']['OccurrenceID'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Newest material changes first */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: components['schemas']['EventChange'][];
          };
        };
      };
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  downloadEventCalendar: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        occurrence_id: components['parameters']['OccurrenceID'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Standards-compliant iCalendar document */
      200: {
        headers: {
          /** @description Attachment filename */
          'Content-Disposition'?: string;
          [name: string]: unknown;
        };
        content: {
          'text/calendar': string;
        };
      };
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  getSourceSummary: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Public source summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SourceSummary'];
        };
      };
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  listOperatorSources: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Source operations summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: components['schemas']['OperatorSource'][];
          };
        };
      };
      default: components['responses']['Problem'];
    };
  };
  listCollectionRuns: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: components['parameters']['SourceID'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recent runs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: components['schemas']['CollectionRun'][];
          };
        };
      };
      default: components['responses']['Problem'];
    };
  };
  triggerCollectionRun: {
    parameters: {
      query?: never;
      header: {
        'Idempotency-Key': components['parameters']['IdempotencyKey'];
      };
      path: {
        source_id: components['parameters']['SourceID'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Collection was queued or reconciled by idempotency key */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CollectionRun'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  replayCollectionRun: {
    parameters: {
      query?: never;
      header: {
        'Idempotency-Key': components['parameters']['IdempotencyKey'];
      };
      path: {
        run_id: components['parameters']['RunID'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Replay queued */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CollectionRun'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  acknowledgeIncident: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        incident_id: components['parameters']['IncidentID'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Updated incident */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Incident'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
}
